### ISSUE TITLE
Link type fails to serialize

### ISSUE THREAD

**Issue by aknoerig** [roman-right/beanie#199]
I'm using the `Link` type to model a relation to another collection, but when I try to serialize it, it fails with a strange error: 
````py
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
````
This is in the context of FastAPI, using their `jsonable_encoder`.
I suppose it is failing while trying to encode the link object. Is the encoding of the Link type simply not yet implemented, or am I not seeing something?

Full traceback:

````py
ERROR uvicorn.error:380 – Exception in ASGI application
Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 377, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File ".../lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File ".../lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File ".../lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File ".../lib/python3.10/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File ".../lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File ".../lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File ".../lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File ".../lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File ".../lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File ".../lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File ".../lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File ".../lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File ".../lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File ".../lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File ".../lib/python3.10/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File ".../lib/python3.10/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "..../app/sites/router.py", line 21, in list_sites
    sites_json = jsonable_encoder(sites)
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 115, in jsonable_encoder
    jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 66, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 93, in jsonable_encoder
    encoded_key = jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 145, in jsonable_encoder
    return jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 101, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File ".../lib/python3.10/site-packages/fastapi/encoders.py", line 144, in jsonable_encoder
    raise ValueError(errors)
ValueError: [TypeError("'_thread.lock' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
````

**Comment by aknoerig** [comment]
When I add a custom json encoder for the `Link` type, it works fine.
Quick hack:

````
class Here(Document)
    there: Link(There)

    class Config:
            json_encoders = {
                Link: lambda v: { "_id": str(v.ref.id) },
            }
````

A clean version of this as part of the Link class would probably be sufficient.

**Comment by aknoerig** [comment]
A slightly cleaner version that retains all the DBRef properties would look like this:

````py
    class Config:
        json_encoders = {
            Link: lambda v: { 
                "$id": str(v.ref.id),
                "$collection": v.ref.collection,
                "$database": v.ref.database
            }
        }
````

**Comment by jsenecal** [comment]
> When I add a custom json encoder for the `Link` type, it works fine. Quick hack:
> 
> ```python
> class Here(Document)
>     there: Link(There)
> 
>     class Config:
>             json_encoders = {
>                 Link: lambda v: { "_id": str(v.ref.id) },
>             }
> ```
> 
> A clean version of this as part of the Link class would probably be sufficient.

Looks like you are using `Link(There)` instead of `Link[There]` (parenthesis vs brackets) as per the [documentation](https://roman-right.github.io/beanie/tutorial/relations/) could that be the root cause of your issues ?

**Comment by aknoerig** [comment]
Thanks, good point–but no, that was just an oversight while typing up the issue here. 😄
