### ISSUE TITLE
Error with update_dict for PydanticObjectId __modify_schema__ when using with FastAPI

### ISSUE THREAD

**Issue by Nihczsche** [roman-right/beanie#22]
Hi,

I am new with python web development, so I am sorry if I missed something. From beanie version 4.0.0 onwards, I have been having issue with the change from update to update_dict method in __modify_schema__ for PydanticObjectId:

`(condaenv) user@ubuntu-Ubuntu:~/Documents/projects/project/backend/project$ uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [58319] using statreload
/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/jose/backends/cryptography_backend.py:18: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes, int_to_bytes
INFO:     Started server process [58321]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:50488 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50488 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:50492 - "GET /docs HTTP/1.1" 200 OK
INFO:     127.0.0.1:50492 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/fastapi/applications.py", line 152, in openapi
    return JSONResponse(self.openapi())
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/fastapi/applications.py", line 130, in openapi
    self.openapi_schema = get_openapi(
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/fastapi/openapi/utils.py", line 354, in get_openapi
    definitions = get_model_definitions(
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/fastapi/utils.py", line 24, in get_model_definitions
    m_schema, m_definitions, m_nested_models = model_process_schema(
  File "pydantic/schema.py", line 548, in pydantic.schema.model_process_schema
  File "pydantic/schema.py", line 589, in pydantic.schema.model_type_schema
  File "pydantic/schema.py", line 236, in pydantic.schema.field_schema
  File "pydantic/schema.py", line 303, in pydantic.schema.get_field_schema_validations
  File "/home/user/anaconda3/envs/condaenv/lib/python3.9/site-packages/beanie/odm/fields.py", line 43, in __modify_schema__
    field_schema.update_dict(
AttributeError: 'dict' object has no attribute 'update_dict'`

I looked through the code and saw that there is a function update_dict in general_utils.py, however this is a function and not a method. Is there some library that I am missing? I used pip to install the package previously, and poetry to install as well, but encountered the same error.

Thanks for your help.

**Comment by roman-right** [comment]
Hi @Nihczsche ,
Thank you very much for this catch. 
It is fixed in 0.4.3
