### ISSUE TITLE
BUG: fetch_links=True does not work

### ISSUE THREAD

**Issue by mbl-95** [roman-right/beanie#250]
Hi,

I am trying to retrieve documents from the DB (using the "get" classmethod) and I want to retrieve the linked documents as well. However, that does not work and I get the following error:

```
FieldPath field names may not start with '$'., full error: 
{'operationTime': Timestamp(1651142380, 1), 'ok': 0.0, 
'errmsg': "FieldPath field names may not start with '$'.", 'code': 16410, 'codeName': 
'Location16410', '$clusterTime': {'clusterTime': Timestamp(1651142380, 1), 
'signature': {'hash': b'|Cnf\xb8\xdev,\xf4\x9c\xf6\x92\x0f\xfcX\xbcy\x8a1\xf0', 'keyId': 7061329875650478083}}}
```

If I try with fetch_links=False, I can successfully get the object back, but without getting the data for the linked document (instead I get a Link object of the linked class). Same is true for find and find_many - they are not able to fetch the links without raising the error.

Does not neccessarily seem to be a Beanie problem, but have you experienced this before?

**Comment by roman-right** [comment]
Hey! Sorry for the delay.
Could you pls provide a code snippet, that reflects this problem? It is potentially an important bug.

**Comment by kounelios13** [comment]
@roman-right  I can confirm the following behaviour. I am doing MyModel.find_all(fetch_links=True) and I get only the beanie.odm.fielda.Link object

**Comment by tsabsch** [comment]
Hi. I have the same behaviour, but was able to link it to the used MongoDB version. To be specific, this only occurs with Mongo 4.2. In Mongo 4.4 and newer `fetch_links=True` works as expected.

MWE if still interesting:

```python
import asyncio

from beanie import Document, Link, WriteRules, init_beanie
from motor.motor_asyncio import AsyncIOMotorClient


class Door(Document):
    height: int = 2
    width: int = 1


class House(Document):
    name: str
    door: Link[Door]


async def main():
    client = AsyncIOMotorClient("mongodb://localhost:27017")
    await init_beanie(database=client.db_name, document_models=[Door, House])

    await House(name="myhouse", door=Door()).save(link_rule=WriteRules.WRITE)

    print(await House.find(House.name == "myhouse", fetch_links=True).to_list())
    # with Mongo 4.2:
    # > pymongo.errors.OperationFailure: FieldPath field names may not start with '$'., full error: {'ok': 0.0, 'errmsg': "FieldPath field names may not start with '$'.", 'code': 16410, 'codeName': 'Location16410'}
    # with Mongo 4.4:
    # > [House(id=ObjectId('6374d12511bd4ab7a38b6bd5'), revision_id=None, name='myhouse', door=Door(id=ObjectId('6374d12511bd4ab7a38b6bd4'), revision_id=None, height=2, width=1))]


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by Abashinos** [comment]
@roman-right We're having a hard time with this issue as well (as expressed in this [question](https://github.com/roman-right/beanie/discussions/456)), since we're using MongoDB 4.0 and it would be quite challenging to upgrade.

Turns out monkey-patching `$set` with `$addFields` causes the same error as @mbl-95 reported originally.

Looks like the minimum MongoDB version this pipeline in `beanie.odm.utils.find` module is going to work is 4.4, which seems to me like a big ask from users since MongoDB changed its license policy to SSPL before 4.4, preventing many enterprises from using anything newer than 4.0.something.

Please consider providing a 4.0-compatible backport.

Thank you!

**Comment by Abashinos** [comment]
> This issue is stale because it has been open 30 days with no activity.

bump

**Comment by smeggingsmegger** [comment]
Bump

**Comment by resulyrt93** [comment]
still not working :/

**Comment by Abashinos** [comment]
> This issue is stale because it has been open 30 days with no activity.

bonk

**Comment by Abashinos** [comment]
We've just hit the same roadblock related to this issue, now in a place where a rather ugly crutch is now going to be required in order to even make links works at all (never mind the optimization concerns).
@roman-right could you please provide an ETA or priority update for this one?
Thank you.

**Comment by roman-right** [comment]
Hi @Abashinos 

The problem is that in 4.4 there are some aggregation syntax updates, that make lookup operations more powerful.

For example, we have two collections. `houses` and `windows`

One house can contain links to more than one window.

Houses:

```json
{
  "_id": "house_1",
  "windows": [
    {
      "$ref": "windows",
      "$id": "window_1"
    },
    {
      "$ref": "windows",
      "$id": "window_2"
    }
  ],
  "name": "test",
  "height": 0
}
```

Windows:
```json
[
  {
    "_id": "window_1",
    "x": 1,
    "y": 1
  },
  {
    "_id": "window_2",
    "x": 2,
    "y": 2
  }
]
```

To fetch links the next aggregation (simplified) is needed:

```json
[
  {
    "$lookup": {
      "from": "windows",
      "let": {
        "link_id": "$windows.$id"
      },
      "as": "windows",
      "pipeline": [
        {
          "$match": {
            "$expr": {
              "$in": [
                "$_id",
                "$$link_id"
              ]
            }
          }
        }
      ]
    }
  }
]
```

But 4.2 doesn't support this notation: `"link_id": "$windows.$id"`.

I didn't find any workarounds for this yet. Any suggestions or PRs (even better) are welcome

**Comment by Abashinos** [comment]
Hi Roman,
Thanks a lot for the comprehensive answer.

What do you think about me providing a PR raising a `NotImplementedError` (or a more relevant one) based on this MongoDB version mismatch? It seems to me that bailing with a relevant message right there would be good enough (I don't feel qualified to develop a backport unfortunately).

Maybe a warning in API docs as well? Probably just a warning note somewhere in the Relations sections, doesn't feel warranted to declare incompatibility with MongoDB <4.4

**Comment by roman-right** [comment]
That makes sense, thank you.

I plan to change the way I store the database version soon. I'll add the respective exception for this case when I'll work on this (this month).

The doc should be also updated, yup

**Comment by Abashinos** [comment]
> That makes sense, thank you.
> 
> I plan to change the way I store the database version soon. I'll add the respective exception for this case when I'll work on this (this month).
> 
> The doc should be also updated, yup

Check this out: https://github.com/roman-right/beanie/pull/560

**Comment by petrovao87** [comment]
steel not working mdb v7.0.2

**Comment by rzadrzi** [comment]
I have the same issue, it's not working for me either.

**Comment by alexkrytsky** [comment]
fetch_link with a single reference does work. However, List[Link[Door]] doesn't work. List of links seems not to be supported still. mdb: v5

**Comment by MaheshSinthu** [comment]
Hey! 👋

You got this error because in Beanie when you do:
users = await User.find_all(fetch_links=True).to_list()

under the hood it uses a MongoDB aggregation cursor that is NOT awaitable directly — so trying to await it throws:

TypeError: object AsyncIOMotorLatentCommandCursor can't be used in 'await' expression

fetch_links=True makes Beanie fetch linked documents with aggregation.

But Motor’s aggregation cursor is a lazy cursor, and Beanie’s .to_list() tries to await it incorrectly.

So the call fails.

#####################https://github.com/BeanieODM/beanie/pull/2 days i try to solve this error but i can't do it.
Versions i used
Name: motor
Version: 3.7.1
Name: pymongo
Version: 4.13.2
Name: beanie
Version: 2.0.0
Name:Python
Version : 3.10.9

######################my source code
@router.get("/users-fetch-links") # error code
async def list_users():
users = await User.find_all(fetch_links=True).to_list()
result = []

for user in users:
    result.append({
        "id": str(user.id),
        "name": user.name,
        "email": user.email,
        "age": user.age,
        "role_name": user.role.name  # This works because it's fetched
    })

return result
########################come to this error

500 Internal Server Error

Traceback (most recent call last):
...
File "app/routes/user.py", line 106, in list_users
 users = await User.find_all(fetch_links=True).to_list()

File "beanie/odm/queries/cursor.py", line 64, in to_list
 cursor = await self.get_cursor()

File "beanie/odm/queries/find.py", line 675, in get_cursor
 await self.document_model.get_pymongo_collection().aggregate(...)

TypeError: object AsyncIOMotorLatentCommandCursor can't be used in 'await' expression

**Comment by pradanaadn** [comment]
Still not working for the `fetch_links=True`. But I found a way to fetch the links.

```
from datetime import datetime

from beanie import Document, Link
from bson import ObjectId
from pydantic import BaseModel, ConfigDict

from src.core.models.collectors_model import Collector
from src.core.models.products_model import Product
from src.core.models.users_model import User
from src.core.models.vehicle_types_model import VehicleType


class Item(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    qty: float = 0.0
    product: Link[Product] | None = None
    price: float | None = None
    totalPrice: float | None = None
    productId: ObjectId | None = None


class Cost(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    name: str | None = None
    value: float | None = None
    total: float | None = None
    source: str | None = None
    type: str | None = None


class Collect(Document):
    model_config = ConfigDict(arbitrary_types_allowed=True)
    items: list[Item] = []
    status: str | None = None
    currency: str | None = None
    distance: float | None = None
    createdAt: datetime
    collectorId: Link[Collector] | None = None
    vehicleTypeId: Link[VehicleType] | None = None
    costs: list[Cost] = []
    createdById: Link[User] | None = None

    class Settings:
        name = "collects"


```

Below is the workaround that fetches all the links.

```

results = await Collect.find(
        And(
            Collect.createdAt >= start_date,
            Collect.createdAt < end_date,
        ),
    ).to_list()
[await result.fetch_all_links() for result in results]
```


```
Python 3.14.0

Name: pymongo
Version: 4.15.3
Location: /home/pradana-ubuntu/Documents/Projects/wwwaste-data-pipeline/.venv/lib/python3.14/site-packages
Requires: dnspython
Required-by: beanie


Name: beanie
Version: 2.0.0
Location: /home/pradana-ubuntu/Documents/Projects/wwwaste-data-pipeline/.venv/lib/python3.14/site-packages
Requires: click, lazy-model, pydantic, pymongo, typing-extensions
Required-by:


```

MongoDB Stats
```
Stats

4 DBs
65 Collections

Cluster

Replica Set atlas-rde7i6-shard-0
3 Nodes

Edition

MongoDB 8.0.15 Atlas

```
