### ISSUE TITLE
[BUG] get_motor_collection() returning `None`

### ISSUE THREAD

**Issue by tistaharahap** [roman-right/beanie#440]
Thank you for the great work done in Beanie, it simplified my life significantly.

**Describe the bug**

This is a DB Client I wrote:

```python
class MongoClient:
    def __init__(self):
        client_options = {'appname': self.__class__.__name__}
        self.client = AsyncIOMotorClient(MONGO_URL, **client_options)
        self.client.get_io_loop = asyncio.get_running_loop

        self.is_testing = TESTING == Environments.Testing.value

    @property
    def db_name(self) -> str:
        db_postfix = ENV

        return f'{svc}-{db_postfix}'

    @abstractmethod
    async def initialize(self):
        raise NotImplementedError('MongoClient.initialize() must be implemented')

    @asynccontextmanager
    async def transaction(self) -> AsyncIOMotorClientSession:
        async with await self.client.start_session() as session:
            async with session.start_transaction():
                yield session
```

The `initialize()` method is implemented like below:

```python
class MongoClientNumberOne(MongoClient):
    async def initialize(self):
        collections = [
            Service,
            ...
        ]
        await init_beanie(database=self.client[self.db_name], document_models=collections)
```

The way I use the Mongo client is to declare it as a dependency in FastAPI routes like below:

```python
class MongoClientDependency:
    def __init__(self, db_type: Type[T]):
        if db_type == MongoClientNumberOne:
            self.client = MongoClientNumberOne()
        elif db_type == MongoClientNumberTwo:
            self.client = MongoClientNumberTwo()
        else:
            raise ValueError("Invalid DB Type given")

    async def __call__(self, request: Request) -> MongoClientNumberOne | MongoClientNumberTwo:
        await self.client.initialize()
        return self.client
```

```python
class Context:
    def __init__(
        self,
        access_token: str | None = None,
        permissions: List[Permissions] | None = None,
        mongo_client: MongoClientNumberOne | None = None,
        mongo_session: AsyncIOMotorClientSession | None = None,
    ):
        self.access_token: str = access_token
        self.permissions: List[Permissions] = permissions

        self.mongo_client: AsyncIOMotorClient = mongo_client
        self.mongo_session: AsyncIOMotorClientSession = mongo_session
        if self.mongo_client:
            self.db_name: str = self.mongo_client.db_name

        self.current_user: User | None = None
        self.current_service: Service | None = None

    @classmethod
    @asynccontextmanager
    async def plain(
        cls, mongo_session: AsyncIOMotorClientSession | None = None, mongo_client: MongoClientNumberOne | None = None
    ) -> Context:
        yield cls(mongo_session=mongo_session, mongo_client=mongo_client)
```

```python
@router.get(
    '/blog/posts',
    summary='Get latest blog posts',
    tags=['Blog'],
    response_model=List[BlogPost],
    responses={503: {'model': ErrorResponse}},
)
async def get_latest_blog_posts(mongo_client: MongoClientNumberOne = Depends(MongoClientDependency(MongoClientNumberOne))):
    async with mongo_client.transaction():
        async with Context.plain():
            return await Blog.get_latest_posts()
```

The problem that I see in Sentry is that at times, read/write queries encountered the `motor_collection` in `ItemSettings` is `None`. A screenshot for this below:

<img width="899" alt="Screen Shot 2022-12-06 at 12 27 49 PM" src="https://user-images.githubusercontent.com/535612/205859573-5b9d9a3f-30ae-499e-816d-684f52fe642f.png">

Unfortunately this happens randomly and intermittent. Usually when there's no traffic and new traffic comes, these errors popped up.

**To Reproduce**

At the start, we almost succeeded in replicating this by creating this test, not so many requests but very high concurrency. Before the codes I wrote above, we have an async context manager that was buggy which is now fixed and the test below passed.

```python
@pytest.mark.asyncio
async def test_concurrency(client: TestClient, individual_user: (RegisterRequest, str, str)):
    token = individual_user[2]

    async def get_profile():
        headers = {'Authorization': f'Bearer {token}'}
        response = await asyncify(client.get)(headers=headers, url='/me')
        assert response.status_code == 200

    async def get_wishlist():
        headers = {'Authorization': f'Bearer {token}'}
        response = await asyncify(client.get)(headers=headers, url='/wishlist')
        assert response.status_code == 200

    async def get_txn():
        headers = {'Authorization': f'Bearer {token}'}
        url = '/transactions?limit=10&skip=0&statuses=submitted,accepted,waitlisted,pending-signature,pending-funding,funds-received,in-execution,completed,unsuccessful'
        response = await asyncify(client.get)(headers=headers, url=url)
        assert response.status_code == 200

    for i in range(10):
        print(f'Iteration {i} - Enter')
        await asyncio.gather(get_profile(), get_wishlist(), get_txn(), get_profile(), get_wishlist(), get_txn())
        print(f'Iteration {i} - Exit')
```

The bug is still happening though, `motor_collection` sometimes still returns `None`.

**Expected behavior**

`self.document_model.get_motor_collection()` should return the collection.

**Additional context**

I'm happy to elaborate more with code examples.

**Comment by roman-right** [comment]
Hey @tistaharahap
Thank you!
I face this behavior too, but could not catch it. It happens in my case only if there are parallel calls. Not sure if this guy is the same. I'll try your code to see, what's happening and will get back to you.

**Comment by tistaharahap** [comment]
Hey @roman-right, thanks for the reply and for writing Beanie, love it!

Something to add, at the moment all the errors that are recorded in Sentry is coming from Beanie's read/write queries. This led me to do my own queries and I wrote something like this for reads and do have some more funcs for writes also.

```python
async def monq_find_many(
    model: Type[TD],
    query: Dict[str, Any],
    *,
    project_to: Type[T] | None = None,
    skip: int = 0,
    limit: int = 0,
    sort: List[Tuple[str, int]] | None = None,
) -> List[T] | List[Dict] | List:
    coll = model.get_settings().motor_db[model.get_settings().name]
    if coll is None:
        raise EnvironmentError(f'Uninitialized collection: {model.Settings.name}')

    _cursor = coll.find(query, skip=skip, limit=limit, sort=sort)

    results = []
    async for doc in _cursor:
        results.append(doc)

    if not results or len(results) == 0:
        return []

    if not project_to:
        return results

    return [project_to(**result) for result in results]
```

Emphasis on this line:

```python
coll = model.get_settings().motor_db[model.get_settings().name]
```

I don't see any more errors by rewriting my codes to use the above. It seems that there's something going on with Beanie's collection getter? The reason why I haven't rewrite more of the codes to use the above is because of `fetch_links` which I use a lot. I'll keep monitoring and see what other information I can put here.

**Comment by roman-right** [comment]
It looks like I caught a problem on my side. Most likely we are victims of the async-await pattern advantages :)

I `init_beanie` more than once (It looks like you too) inside of the single event loop. There are moments, where `init_beanie` started, but is not finished from one side (settings inited, but the collection was not created yet and it is waiting for the response from the MongoDB) and during the switch on `await` another async operation is happening (find query for example). The collection attribute is None at this moment - Error.
The solution, for now, is to run init_beanie exactly once (make a flag to check if it was invited already)

I'll make a singleton mode for the initializer soon. It will be configurable and, in this mode, the `init_beanie` call will not reinit if it already did it.

**Comment by tistaharahap** [comment]
Ah I see, understood @roman-right, makes total sense :)

I called `init_beanie` on every request, so instead I should've just called it once right? Assuming this then for a FastAPI application, it should only be called while setting up the `FastAPI` app object I suppose?

**Comment by roman-right** [comment]
Yes, correct. For the FastAPI app you can use `@app.on_event("startup")`:
```python
app = FastAPI()


@app.on_event("startup")
async def app_init():
    # CREATE MOTOR CLIENT
    client = motor.motor_asyncio.AsyncIOMotorClient(Settings().mongodb_dsn)

    # INIT BEANIE
    await init_beanie(
        client.beanie_db,
        document_models=[HouseAPI, WindowAPI, DoorAPI, RoofAPI],
    )

    # ADD ROUTES
    app.include_router(house_router, prefix="/v1", tags=["house"])
```

**Comment by tistaharahap** [comment]
Awesome, thanks @roman-right, appreciate it!

**Comment by tistaharahap** [comment]
For reference, with your suggestion, I rewrote the FastAPI dependency to look like below:

```python
class MongoClientDependency:
    client: ClassVar[MongoClient | None] = None
    has_initialized: ClassVar[bool] = False

    def __init__(self):
        MongoClientDependency.client = MongoClient()
        MongoClientDependency.has_initialized = False

    async def __call__(self, request: Request) -> MongoClient:
        if not MongoClientDependency.has_initialized:
            await MongoClientDependency.client.initialize()
            MongoClientDependency.has_initialized = True

        return MongoClientDependency.client
```

Going to try this and report back here.

**Comment by roman-right** [comment]
Hey @tistaharahap 
Did it fix your problem?

**Comment by tistaharahap** [comment]
> Hey @tistaharahap Did it fix your problem?

Hey @roman-right apologies for the late reply. Unfortunately the changes didn't live up to expectations. For my use case, I need the transactional capabilities of MongoDB so I will need to create a session every time there's a new request. In order for that to happen, I inject the MongoDB client into every request. The catch is `@app.on_event("startup")` is not working at all for me, if I put the codes to `init_beanie()` there, it's as if if the codes are not called.

This seems to be FastAPI related but what you said about making a Singleton out of initializing Beanie would solve this problem I suppose.

**Comment by Iazzetta** [comment]
I've been facing this problem for a long time and I just found this Thread. This explains many of the anomalies I have been experiencing.

**Comment by Iazzetta** [comment]
Is there a way to change the database/collection without initialize Beanie again? like:

```
for model in [Model1, Model2]:
    model.set_database(...)
```

or check if collection already loaded before proceed request?

**Comment by amirsalaar** [comment]
I also have a similar issue when using pytest.
However, I am not calling `init_beanie` multiple times. My database is scoped to `function` so it drops the db and collections everytime before each test. So `init_beanie` shouldn't be an issue in my case (?)

I am not also testing concurrently. It's just serialized testing in one thread. (i am also running only one of my tests and getting this errro -- so the event loop is not calling `init_beani` multiple times)

**Comment by ltieman** [comment]
Hey @roman-right we are still having this issue, we have ensured that we are only calling init_beanie once, yet are getting this sporatically.  We've tried scaling down our fast-api workers to 1, but are still having collections coming back with get_motor_collection returning none.

This is our singleton:


```
beanie_init: bool = False
class MongoSingleton:
    client: AsyncIOMotorClientSession = AsyncIOMotorClient(settings.MONGO_URI, maxPoolSize=400, minPoolSize=50)

    async def startup(self):
        global beanie_init
        if not beanie_init:
            from libraries.mongo.models import models as all_models
            global all_models
            for model in all_models:
                model.model_rebuild(force=True)
            await init_beanie(self.client.plantbid, document_models=all_models)

            beanie_init = True

mongo_singleton = MongoSingleton()```

We are using this to set up the lifecycle event:
```
@asynccontextmanager
async def startup_event(app: FastAPI):
    from libraries.mongo.mongodb import mongo_singleton
    await mongo_singleton.startup()
    yield


fastapi_app = FastAPI(lifespan=startup_event)```



and this is our stacktrace:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 364, in _sentry_patched_asgi_app
    return await middleware(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 146, in _run_asgi3
    return await self._run_app(scope, receive, send, asgi_version=3)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 241, in _run_app
    raise exc from None
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/asgi.py", line 234, in _run_app
    return await self.app(
           ^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 157, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 256, in _sentry_exceptionmiddleware_call
    await old_call(self, scope, receive, send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 157, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/sentry_sdk/integrations/starlette.py", line 157, in _create_span_call
    return await old_call(app, scope, new_receive, new_send, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/libraries/api_resources/resource_type.py", line 347, in get_by_id
    return await self.get_by_id_crud(id=id, engine=engine, user=user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/libraries/api_resources/mongo_resource.py", line 286, in get_by_id_crud
    data = await self.model.find_one(*new_query, fetch_links=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 1042, in __await__
    document = yield from self._find_one().__await__()  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 998, in _find_one
    return await self.document_model.find_many(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 701, in first_or_none
    res = await self.limit(1).to_list()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/queries/cursor.py", line 72, in to_list
    cursor = self.motor_cursor
             ^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 674, in motor_cursor
    ] = self.build_aggregation_pipeline()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 623, in build_aggregation_pipeline
    ] = construct_lookup_queries(
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/utils/find.py", line 29, in construct_lookup_queries
    construct_query(
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/utils/find.py", line 56, in construct_query
    raise e
  File "/Users/jkinsey/projects/plantbid/monorepo/python_services/venv/lib/python3.11/site-packages/beanie/odm/utils/find.py", line 54, in construct_query
    link_info.document_class.get_motor_collection().name
AttributeError: 'NoneType' object has no attribute 'name'
```
