### ISSUE TITLE
[BUG] init_beanie() doesn't work properly sometimes

### ISSUE THREAD

**Issue by yallxe** [roman-right/beanie#561]
**Describe the bug**
Sometimes `init_beanie()` raises pydantic's validation error.
```ERROR:    Traceback (most recent call last):
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "D:\Dev\[hidden]\[hidden]\app\database\__init__.py", line 22, in init_database
    await init_beanie(
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\beanie\odm\utils\init.py", line 530, in init_beanie
    await Initializer(
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\beanie\odm\utils\init.py", line 89, in __await__
    yield from self.init_class(model).__await__()
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\beanie\odm\utils\init.py", line 500, in init_class
    await self.init_document(cls)
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\beanie\odm\utils\init.py", line 358, in init_document
    self.init_document_fields(cls)
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\beanie\odm\utils\init.py", line 202, in init_document_fields
    check_nested_links(link_info, prev_models=[])
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\beanie\odm\utils\init.py", line 180, in check_nested_links
    nested_link_info = detect_link(v)
                       ^^^^^^^^^^^^^^
  File "C:\Users\yallxe\AppData\Local\pypoetry\Cache\virtualenvs\[hidden]-gdEMt55_-py3.11\Lib\site-packages\beanie\odm\utils\relations.py", line 30, in detect_link
    return LinkInfo(
           ^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for LinkInfo
model_class
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)

ERROR:    Application startup failed. Exiting.
```

**Research**
Sometimes, `field.sub_fields[0].type_` (`model_class`) occurs to be (in my case) `ForwardRef('Tariff')`.

**Additional context**
Sometimes it is initializing correctly, without any issues, but sometimes this problem appears. No code changes even required.

**Comment by tcha0** [comment]
Hi,
I *consistently* get the same error as yallxe on either Python 3.9, 3.10 or 3.11 when I run the following  [.py file](https://gist.github.com/tcha0/3fe40ebe58e01432e669c08fb0825185.).
Dropping to PDB, I get `<class 'typing.ForwardRef'>` when  I run `type(field.sub_fields[0].type_)` while `LinkInfo.model_class` expects `Type[BaseModel]`.

**Comment by yallxe** [comment]
It is probably an internal bug with forward refs. I didn't even know such an issue could occure.

@roman-right

**Comment by roman-right** [comment]
Hi @yallxe , @tcha0 ,

Thank you for the report! Could you please provide a small example to reproduce it?

**Comment by yallxe** [comment]
@tcha0 already did.

**Comment by roman-right** [comment]
Oh, I missed the link. True

**Comment by roman-right** [comment]
I'll work on this today. But the problem could be complicated as I have to deal with Pydantic logic.

The workaround:

```python
from typing import List

from beanie import Document, BackLink, Link, init_beanie
from motor.frameworks.asyncio import asyncio
from pydantic import Field
from motor.motor_asyncio import AsyncIOMotorClient


class House(Document):
    name: str
    door: Link["Door"]
    owners: List[Link["Person"]]


class Door(Document):
    height: int = 2
    width: int = 1
    house: BackLink[House] = Field(original_field="door")


class Person(Document):
    name: str
    house: List[BackLink[House]] = Field(original_field="owners")


async def main():
    House.update_forward_refs()
    client = AsyncIOMotorClient("mongodb://beanie:beanie@127.0.0.1:27017")
    await init_beanie(
        database=client.testdb,
        document_models=[Door, House, Person],
    )


if __name__ == "__main__":
    asyncio.run(main())
```

The line `House.update_forward_refs()` will do the trick

**Comment by roman-right** [comment]
Or, what can look crazy, you can change the order of the documents to have the one with Links in the first place:

```python
    client = AsyncIOMotorClient("mongodb://beanie:beanie@127.0.0.1:27017")
    await init_beanie(
        database=client.testdb,
        document_models=[House, Door, Person],
    )
```

**Comment by yallxe** [comment]
At least I know why my problem occurs only **sometimes**. The problem is that I'm using `Document.__subclasses__()` instead of providing all the documents manually, and the result order is random.

**Comment by roman-right** [comment]
@yallxe @tcha0
The fix is here: https://github.com/roman-right/beanie/pull/566
I'll merge it on Monday together with some other fixes.

**Comment by yallxe** [comment]
@roman-right, Just want to remember :)

**Comment by roman-right** [comment]
@yallxe yup. I have been finishing with another fix. You can find it in `1.9.1`
