### ISSUE TITLE
[BUG] Native Python syntax for boolean conditions results in error

### ISSUE THREAD

**Issue by bwhli** [roman-right/beanie#605]
**Describe the bug**

I have a model like this:

```
class MachinNft(Document):
    number: Indexed(int)
    name: Indexed(str)
    generation: Indexed(str)
    blockchain: Indexed(str)
    image_uri: Indexed(str)
    image_uri_color: Indexed(str) = None
    metadata_uri: Indexed(str)
    metadata_uri_color: Indexed(str) = None
    rarity_class: Indexed(str)
    rarity_rank: Indexed(int)
    rarity_score: Indexed(float)
    attributes: list[MachinNftAttribute]
    is_revealed: bool = False
    is_colored: bool = False
    mint_timestamp: Indexed(datetime) = None
    mint_tx_hash: Indexed(str) = None
    reveal_tx_hash: Indexed(str) = None

    class Settings:
        name = "machinCollection"
```

In my API, I query MongoDB like so:

```
machin_nfts = (
                    await MachinNft.find(MachinNft.is_revealed is True)
                    .sort(sort_query)
                    .limit(limit * 2)
                    .skip(limit * page)
                    .to_list()
                )
```

Since `is_revealed` is a boolean, I write `MachinNft.is_revealed is True`. This results in an error:

```
[1] ERROR - 2023-07-04 10:18:10,926 - litestar - config - exception raised on http connection to route /collections/htmx/grid/machin/prime
[1]
[1] Traceback (most recent call last):
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 157, in __call__
[1]     await self.app(scope, receive, send)
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 77, in handle
[1]     response = await self._get_response_for_request(
[1]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 129, in _get_response_for_request
[1]     response = await self._call_handler_function(
[1]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 158, in _call_handler_function
[1]     response_data, cleanup_group = await self._get_response_data(
[1]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/litestar/routes/http.py", line 207, in _get_response_data
[1]     data = await route_handler.fn.value(**parsed_kwargs)
[1]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/Users/brianli/Documents/GitHub/nozomi.world/nozomi_world/controllers/app/collections.py", line 434, in get_htmx_prime_machin_grid
[1]     await MachinNft.find(MachinNft.is_revealed is True)
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/beanie/odm/queries/cursor.py", line 72, in to_list
[1]     cursor = self.motor_cursor
[1]              ^^^^^^^^^^^^^^^^^
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 656, in motor_cursor
[1]     filter=self.get_filter_query(),
[1]            ^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 108, in get_filter_query
[1]     self.prepare_find_expressions()
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/beanie/odm/queries/find.py", line 96, in prepare_find_expressions
[1]     self.find_expressions[i] = convert_ids(
[1]                                ^^^^^^^^^^^^
[1]   File "/Users/brianli/Library/Caches/pypoetry/virtualenvs/nozomi-world-D70FuMi0-py3.11/lib/python3.11/site-packages/beanie/odm/utils/relations.py", line 98, in convert_ids
[1]     for k, v in query.items():
[1]                 ^^^^^^^^^^^
[1] AttributeError: 'bool' object has no attribute 'items'
```

If I change the filter condition to `MachinNft.is_revealed == True`, then things work as expected. The issue is my linter in my CI/CD pipeline changes it back to `MachinNft.is_revealed is True`.

**Comment by bwhli** [comment]
For the time being, I've reverted back to MongoDB syntax:

```
machin_nfts = (
                    await MachinNft.find({"is_revealed": True})
                    .sort(sort_query)
                    .limit(limit * 2)
                    .skip(limit * page)
                    .project(MachinNftCollectionGridShortView)
                    .to_list()
                )
```

**Comment by roman-right** [comment]
Hi @bwhli,

The thing is, it is impossible to override the behavior of the `is` operator. You can use `==`, which I patched for the document fields. In the MongoDB context, `is` and `==` are the same thing.

**Comment by bwhli** [comment]
I see. It took me a while to figure out my linter was editing it automatically, haha. I will stick with the native syntax to avoid that. Cheers!
