### ISSUE TITLE
Issues with initializing a View

### ISSUE THREAD

**Issue by gsakkis** [roman-right/beanie#715]
I run into two issues when passing a `View` model to  `init_beanie`:

1. The result of [`list_collection_names`](https://github.com/roman-right/beanie/blob/main/beanie/odm/utils/init.py#L646-L649) contains "system.views" instead of my view name. This means that the condition `if self.recreate_views or cls._settings.name not in collection_names` is always True and it always attempt to (re)create the view.

2. I am getting an intermittent, non-deterministic exception from PyMongo: `pymongo.errors.OperationFailure: Namespace ... is a view, not a collection`. Apparently this happens in a thread so it doesn't stop the overall execution but it's still worrying. Full traceback:
```
Future exception was never retrieved
future: <Future finished exception=OperationFailure("Namespace [...] is a view, not a collection, full error: {'ok': 0.0, 'errmsg': 'Namespace [...] is a view, not a collection', 'code': 166, 'codeName': 'CommandNotSupportedOnView'}")>
Traceback (most recent call last):
  File ".../lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File ".../lib/python3.10/site-packages/pymongo/collection.py", line 2173, in drop_indexes
    self.drop_index("*", session=session, **kwargs)
  File ".../lib/python3.10/site-packages/pymongo/_csot.py", line 108, in csot_wrapper
    return func(self, *args, **kwargs)
  File ".../lib/python3.10/site-packages/pymongo/collection.py", line 2235, in drop_index
    self._command(
  File ".../lib/python3.10/site-packages/pymongo/collection.py", line 310, in _command
    return conn.command(
  File ".../lib/python3.10/site-packages/pymongo/helpers.py", line 315, in inner
    return func(*args, **kwargs)
  File ".../lib/python3.10/site-packages/pymongo/pool.py", line 932, in command
    return command(
  File ".../lib/python3.10/site-packages/pymongo/network.py", line 191, in command
    helpers._check_command_response(
  File ".../lib/python3.10/site-packages/pymongo/helpers.py", line 223, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Namespace [...] is a view, not a collection, full error: {'ok': 0.0, 'errmsg': 'Namespace [...] is a view, not a collection', 'code': 166, 'codeName': 'CommandNotSupportedOnView'}
```

**Comment by gsakkis** [comment]
It turns out both issues were user (my) errors:
- For (1) although `list_collection_names` does include `system.views`, it also includes the view name as well (if it exists). As I was trying out things I was deleting the view and thought that `list_collection_names` showed `system.views` _instead of_ (rather than _in addition to_) the view name.
- For (2) I was calling `drop_indexes` on all models without checking if it's a Document or a View. It's still strange that the error was non deterministic but regardless, `drop_indexes` shouldn't be called on views.
